on:
  schedule:
  - cron: "2 * * * *"
  workflow_dispatch:

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - run: |
          # make file runnable, might not be necessary
          chmod +x "./make_html.sh"
          # 
          run:  bash "./make_html.sh"
          shell: bash
